Sugestia: Style <kbd> as key notation
Coyote-OSS/coyote pull request #685
Opened 2022-02-09 17:35 UTC by danon

Teraz klawisze `<kbd>` nie wyglądają jak klawisze. Pomyślałem że możnaby skopiować po prostu style z edytora.

```
<kbd>Ctrl+Alt</kbd>

> quote

<mark>zaznaczone</mark>
```

Wyglądałoby tak:
![image](https://user-images.githubusercontent.com/13367735/153257487-7fe67e0b-1d40-48d1-9b84-7b66389d0456.png)

Ten czarny styl zostawimy na jakiś inny znacznik, być może na `<mark>`?

2022-02-09 18:34 UTC, adam-boduch requested changes

2022-02-09 18:34 UTC, adam-boduch commented on resources/sass/core/_code.scss
> +  display: inline;
czy to jest potrzebne? chyba domyślnie jest `inline`

2022-02-09 18:34 UTC, adam-boduch commented on resources/sass/core/_code.scss
> +  border-radius: 4px;
to chyba też nie jest potrzebne. zostanie wzięty domyślny `border-radius` z bootstrapa

2022-02-09 18:34 UTC, adam-boduch commented on resources/sass/core/_code.scss
> +  padding: 0.1em 0.3em 0.1em 0.2em;
W `resources/sass/helpers/_variables.scss` możesz przypisać wartości zmiennym: `$kbd-padding-y` oraz `$kbd-padding-x`. Bootstrap sobie już wygeneruje odpowiedni kod html :)

2022-02-09 18:34 UTC, adam-boduch commented on resources/sass/core/_code.scss
> +  color: #232629;
j/w tylko zmienna `$kbd-color`

2022-02-09 18:34 UTC, adam-boduch commented on resources/sass/core/_code.scss
> +  background-color: #e7e7e7;
`$kbd-bg`

2022-02-09 18:34 UTC, adam-boduch commented on resources/sass/core/_code.scss
> +  box-shadow: 0 0px 1px hsl(210deg, 8%, 5% / 15%), inset 0 1px 0 0 hsl(0, 0%, 100%);
`$kbd-box-shadow`

2022-02-09 18:59 UTC, Danon commented
@adam-boduch Wymienić wszystkie wartości na zmienne? Czy tylko te które podałes?

2022-02-10 07:01 UTC, adam-boduch commented
Tylko te które podałem (zmienne bootstrapa).

2022-02-10 10:09 UTC, Danon commented
> Tylko te które podałem (zmienne bootstrapa).

To to poprawione

2022-02-11 08:26 UTC, Danon commented
@adam-boduch Dobrze zrobiłem? Czy to nie o to chodziło?

2022-02-11 08:50 UTC, adam-boduch requested changes

2022-02-11 09:11 UTC, Danon commented
@adam-boduch Updated

2022-02-11 09:13 UTC, adam-boduch approved these changes

2022-02-11 09:13 UTC, merged

2022-02-11 11:59 UTC, Danon commented
`$kbd-box-shadow` się nie łapie. Musiałem je dodać z powrotem.